import { api, store } from '../api';
import { content, setActive } from '../layout';
import { bindPagination, esc, pagination, spinner, toast } from '../ui';
import { loadRanks } from '../reference';

let state = { search: '', status: '', page: 1 };
const STATUSES = ['imported', 'outreach_sent', 'cv_requested', 'cv_submitted', 'rejected', 'converted_to_cadet'];

export async function render() {
    setActive('recruitment');
    content(spinner());
    const can = { import: store.hasPermission('recruitment.import'), action: store.hasPermission('recruitment.action'), promote: store.hasPermission('recruitment.promote-to-cadet') };
    const data = await api('/recruitment-candidates', { params: state });
    const root = content('');
    root.innerHTML = `<div class="mx-auto max-w-7xl"><div class="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-indigo-600">Talent pipeline</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-900">Recruitment &amp; Ingestion</h2><p class="mt-1 text-sm text-slate-500">Track prospective cadets from import through verified enrollment.</p></div>${can.import ? '<button id="import-candidates" class="inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700">Import CSV ledger</button>' : ''}</div><div class="overflow-hidden rounded-xl border border-slate-100 bg-white shadow-sm"><div class="flex flex-wrap items-center gap-3 border-b border-slate-100 bg-slate-50/60 p-4"><input id="candidate-search" value="${esc(state.search)}" placeholder="Search candidate, email, or contact…" class="min-w-[220px] flex-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"><select id="candidate-status" class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600"><option value="">All pipeline statuses</option>${STATUSES.map((status) => `<option value="${status}" ${state.status === status ? 'selected' : ''}>${label(status)}</option>`).join('')}</select></div><div id="candidate-list" class="overflow-x-auto"></div><div id="candidate-pagination" class="border-t border-slate-100 px-4 py-3"></div></div></div>`;
    root.querySelector('#candidate-search').addEventListener('keydown', (event) => { if (event.key === 'Enter') { state.search = event.target.value.trim(); state.page = 1; render(); } });
    root.querySelector('#candidate-status').addEventListener('change', (event) => { state.status = event.target.value; state.page = 1; render(); });
    root.querySelector('#import-candidates')?.addEventListener('click', () => importModal());
    renderTable(root, data, can);
}

function renderTable(root, data, can) {
    const list = root.querySelector('#candidate-list');
    if (!data.items.length) { list.innerHTML = '<div class="p-12 text-center text-sm text-slate-400">No recruitment candidates found.</div>'; return; }
    list.innerHTML = `<table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Full name</th><th class="px-4 py-3">Location context</th><th class="px-4 py-3">Contact details</th><th class="px-4 py-3">Skills</th><th class="px-4 py-3">Pipeline status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">${data.items.map((candidate) => `<tr class="hover:bg-slate-50/60"><td class="px-4 py-3 align-top"><div class="font-semibold text-slate-800">${esc(candidate.full_name)}</div><div class="mt-1 text-xs text-slate-400">${esc(candidate.gender || 'Gender not recorded')}</div></td><td class="px-4 py-3 align-top text-xs text-slate-600">${esc([candidate.province?.name_en, candidate.district?.name_en, candidate.local_level, candidate.ward_number ? `Ward ${candidate.ward_number}` : ''].filter(Boolean).join(' · ') || 'Not mapped')}</td><td class="px-4 py-3 align-top"><div class="text-xs font-medium text-slate-700">${esc(candidate.contact_number)}</div><div class="mt-1 text-xs text-slate-400">${esc(candidate.email || 'No email')}</div></td><td class="px-4 py-3 align-top"><div class="flex max-w-48 flex-wrap gap-1">${(candidate.skills || []).slice(0, 4).map((skill) => `<span class="rounded bg-slate-100 px-2 py-0.5 text-xs text-slate-700">${esc(skill)}</span>`).join('') || '<span class="text-xs text-slate-400">—</span>'}</div></td><td class="px-4 py-3 align-top">${statusBadge(candidate.recruitment_status)}</td><td class="px-4 py-3 text-right align-top">${actionMenu(candidate, can)}</td></tr>`).join('')}</tbody></table>`;
    list.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => runAction(button.dataset.action, data.items.find((item) => String(item.id) === button.dataset.id))));
    list.querySelectorAll('[data-promote]').forEach((button) => button.addEventListener('click', () => promoteModal(data.items.find((item) => String(item.id) === button.dataset.promote))));
    const page = root.querySelector('#candidate-pagination'); page.innerHTML = pagination(data.meta); bindPagination(page, (next) => { state.page = next; render(); });
}

function actionMenu(candidate, can) { if (!can.action && !can.promote) return '<span class="text-xs text-slate-300">—</span>'; return `<div class="flex justify-end gap-2">${can.action ? `<details class="relative text-left"><summary class="cursor-pointer list-none rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50">Manage</summary><div class="absolute right-0 z-20 mt-1 w-52 rounded-lg border border-slate-200 bg-white py-1 shadow-lg"><button data-action="outreach" data-id="${candidate.id}" class="block w-full px-3 py-2 text-left text-xs hover:bg-slate-50">Send CV intake template link</button><button data-action="notes" data-id="${candidate.id}" class="block w-full px-3 py-2 text-left text-xs hover:bg-slate-50">Log manual phone notes</button><button data-action="reject" data-id="${candidate.id}" class="block w-full px-3 py-2 text-left text-xs text-rose-600 hover:bg-rose-50">Mark as rejected</button></div></details>` : ''}${can.promote && candidate.recruitment_status !== 'converted_to_cadet' ? `<button data-promote="${candidate.id}" class="rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-indigo-700">Promote</button>` : ''}</div>`; }
async function runAction(action, candidate) { if (action === 'notes') { const notes = window.prompt('Add recruitment phone notes', candidate.notes || ''); if (notes === null) return; await api(`/recruitment-candidates/${candidate.id}`, { method: 'PATCH', body: { notes } }); } else { const recruitment_status = action === 'outreach' ? 'outreach_sent' : 'rejected'; await api(`/recruitment-candidates/${candidate.id}`, { method: 'PATCH', body: { recruitment_status } }); } toast('Candidate pipeline updated.', 'success'); render(); }
function importModal() { modal('Import recruitment CSV', `<p class="text-sm text-slate-500">Upload a CSV exported from Excel or Google Sheets. Duplicate contact numbers are skipped and returned in the import warning log.</p><form id="import-form" class="mt-5"><input name="file" type="file" accept=".csv,text/csv" required class="block w-full rounded-lg border border-slate-200 p-2 text-sm"><div class="mt-5 flex justify-end gap-2"><button type="button" data-close class="rounded-lg border border-slate-200 px-4 py-2 text-sm">Cancel</button><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Start import</button></div></form>`); document.querySelector('#import-form').addEventListener('submit', async (event) => { event.preventDefault(); const result = await api('/recruitment-candidates/import', { method: 'POST', body: new FormData(event.target) }); closeModal(); toast(`${result.imported} imported · ${result.duplicates} duplicates · ${result.skipped} skipped`, 'success'); if (result.warnings?.length) window.alert(`Import warnings:\n\n${result.warnings.join('\n')}`); render(); }); }
async function promoteModal(candidate) { const ranks = await loadRanks(); const username = candidate.full_name.toLowerCase().replace(/[^a-z0-9]+/g, '.').replace(/^\.|\.$/g, '').slice(0, 42); modal(`Promote ${esc(candidate.full_name)} to Cadet`, `<p class="text-sm text-slate-500">Creates a linked active user and cadet record using the pre-filled recruitment profile.</p><form id="promote-form" class="mt-5 space-y-4"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium text-slate-700">Cadet number<input name="cadet_number" placeholder="NCC-XXXXX" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"></label><label class="text-sm font-medium text-slate-700">Verified rank<select name="rank_id" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Select rank</option>${ranks.map((rank) => `<option value="${rank.id}">${esc(rank.name_en)}</option>`).join('')}</select></label><label class="text-sm font-medium text-slate-700">Username<input name="username" value="${esc(username)}" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"></label><label class="text-sm font-medium text-slate-700">Temporary password<input name="password" type="password" required minlength="12" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"></label><label class="text-sm font-medium text-slate-700 sm:col-span-2">Confirm temporary password<input name="password_confirmation" type="password" required minlength="12" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"></label></div><div class="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">${esc(candidate.full_name)} · ${esc(candidate.email || 'No email')} · ${esc(candidate.contact_number)}</div><div class="flex justify-end gap-2"><button type="button" data-close class="rounded-lg border border-slate-200 px-4 py-2 text-sm">Cancel</button><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Confirm promotion</button></div></form>`); document.querySelector('#promote-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.target); await api(`/recruitment-candidates/${candidate.id}/promote`, { method: 'POST', body: Object.fromEntries(form) }); closeModal(); toast('Candidate promoted to active cadet.', 'success'); render(); }); }
function modal(title, body) { document.body.insertAdjacentHTML('beforeend', `<div id="recruitment-modal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><div class="flex items-start justify-between gap-4"><h3 class="text-lg font-bold text-slate-900">${title}</h3><button data-close class="text-slate-400">✕</button></div>${body}</div></div>`); document.querySelectorAll('#recruitment-modal [data-close]').forEach((button) => button.addEventListener('click', closeModal)); }
function closeModal() { document.getElementById('recruitment-modal')?.remove(); }
function label(status) { return status.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function statusBadge(status) { const tones = { imported: 'bg-slate-100 text-slate-600', outreach_sent: 'bg-sky-50 text-sky-700', cv_requested: 'bg-amber-50 text-amber-700', cv_submitted: 'bg-violet-50 text-violet-700', rejected: 'bg-rose-50 text-rose-700', converted_to_cadet: 'bg-emerald-50 text-emerald-700' }; return `<span class="inline-flex rounded-full px-2 py-1 text-xs font-medium ${tones[status] || tones.imported}">${label(status)}</span>`; }
